/**
 * Pure rules for the retained-scan sweep (#578) — no Prisma, so the period and the cutoff it
 * produces are unit-tested on their own.
 *
 * The sweep exists because a card scan is the largest object this app stores — 50–200 MB at
 * scanning resolution, a dozen or more per stockbook — and because a batch reaches a point where it
 * can never be cut into anything again. #567 stamps that moment on the batch's sheets
 * (`ScanSheet.batchDoneAt`): the last tile has left `unidentified`, a consumed tile refuses a
 * re-cut, and from there the retained original's only remaining role is archival.
 *
 * What goes is the **bytes and not the row**. The sheet survives, marked purged, so a re-cut refuses
 * with *the scan has been deleted* and the batch still lists what it held — rather than a missing
 * file surfacing as a read error, which is how a collector learns about it in the worst possible
 * way. The closed-offer sweep made the same call, for the same reason, and its `OfferPhotoGeneration`
 * row survives at `purged` in the same spirit.
 *
 * The grace period, when one is set, is for a narrow but real case: a box that clipped a stamp's
 * perforation by a few pixels is easy to miss at screen scale during the review and is noticed later,
 * looking at the copy's own photo — usually while the parcel is still being worked. Days cover
 * exactly that window. Afterwards the stamp is filed on a card in a box and the answer is to
 * re-photograph the one piece, which is cheap because its ref says where it is.
 */
import {
  RETENTION_FOREVER,
  parseRetentionSetting,
  retentionCutoff,
  retentionPeriodWords,
  retentionTtlMs,
} from "./retention-ttl";

/**
 * What an instance that has configured nothing does with a finished batch's scan: **nothing at
 * all**. The sweep ships off, and this is the deliberate part of it.
 *
 * The arithmetic argues the other way — a card is tens of megabytes, a few parcels a month is tens
 * of gigabytes a year — and an earlier draft of #578 read it that way and proposed thirty days. It
 * was wrong, and what makes it wrong is a line the codebase had already drawn:
 *
 *   > **Generated bytes are the only bytes the app ever deletes on a schedule** (#512), because
 *   > output is disposable and a source is not (#137).
 *
 * A closed offer's collages are *generated*: Regenerate makes them again from the copies' own scans.
 * **A card scan is a source.** A stockbook cannot be re-scanned once it has been broken up, so
 * deleting one on a timer — by default, on an instance whose owner has never opened Settings —
 * breaks a stated invariant rather than merely being aggressive. The invariant survives this feature
 * intact, with one clause added: source bytes are never swept *unless the collector asks for it*,
 * and this is the one place that can be asked.
 *
 * So the capability ships and the schedule does not. #577 put the retention control directly beside
 * the collection's storage figure, which means the collector who actually has a disk problem meets
 * the answer exactly where they notice the problem — and says so themselves, about their own
 * collection, rather than finding it was said for them.
 */
export const DEFAULT_SCAN_SHEET_TTL_MS: number | null = null;

/**
 * How long a finished-with batch keeps its retained scans, in milliseconds, or `null` for keep for
 * ever.
 *
 * The grammar is **#577's, unchanged** and shared through `retention-ttl.ts`: `off` / `never` keeps
 * for ever, `0` sweeps at the next pass, anything else is days. Deliberately not a second
 * vocabulary — the two retention settings sit on one screen, and `0` meaning opposite things on them
 * would be a trap. What is this setting's own is the **default** above, which differs precisely
 * because a scan is a source and a collage is not.
 *
 * Three places speak it — the collection's own `scanSheetTtlDays`, then the environment variable,
 * then that default — which is why this takes the string rather than reading `process.env` itself.
 * `scan-sheet-retention.ts` does the resolving, and is the only module that names the variable.
 */
export function scanSheetTtlMs(raw: string | undefined): number | null {
  return retentionTtlMs(raw, DEFAULT_SCAN_SHEET_TTL_MS);
}

/**
 * How the sweep is configured, in one line for the boot log — the counterpart of the closed-offer
 * purge's own startup line. A deletion that runs on a schedule should say so at boot rather than
 * only when it first fires, and the *off* case is the one an operator most wants confirmed, since
 * off is what an untouched instance does with the bytes it can never make again.
 */
export function describeScanSheetTtl(ttlMs: number | null): string {
  if (ttlMs === null) {
    return "disabled — retained card scans are kept indefinitely";
  }
  if (ttlMs === 0) {
    return "a card scan is deleted at the next sweep after its batch is finished with";
  }
  return `a card scan is deleted ${retentionPeriodWords(ttlMs)} after its batch is finished with`;
}

/** What a collection stores in `scanSheetTtlDays`: `null` = no opinion, defer to the instance;
 * otherwise a canonical value in the grammar above. */
export type ScanSheetTtlSetting = string | null;

/** The canonical way to say *keep for ever*, shared with the closed-offer setting so a stored value
 * and a documented one read the same on both. */
export const SCAN_SHEET_TTL_FOREVER = RETENTION_FOREVER;

/** Canonicalize what the settings form is about to store, or `undefined` when it is not a value this
 * grammar has. Validation lives at this one write site because the read path is deliberately
 * forgiving: a typo must never break a sweep, but it should be refused while the collector is still
 * looking at it. Blank is not an error — it is how the form says *no opinion*, and stores `null`. */
export function parseScanSheetTtlSetting(
  raw: string | null | undefined
): ScanSheetTtlSetting | undefined {
  return parseRetentionSetting(raw);
}

/**
 * The instant a batch must have been finished with *before* for its scans to be swept, or `null`
 * when the sweep is off. Passed `now` rather than reading the clock, so the sweep and its tests
 * agree on one instant.
 */
export function scanSheetCutoff(now: Date, ttlMs: number | null): Date | null {
  return retentionCutoff(now, ttlMs);
}
