-- Manual photo attachments on an offer (#313).
--
-- The generated collages are what a rule produced from the offer's composition. An attachment is
-- what the collector put in the plan by hand: a *specific* photo of a copy in the offer (so a
-- perforation, a flaw or a cancel can be shown on its own), or an arbitrary image uploaded straight
-- to the offer. Both are annotated through the same path as every other tile (#312) — nothing is
-- ever passed through unlabelled.
--
-- The row is the **plan entry**, not the image. That is the whole point of a separate table: the
-- derived/manual distinction has to live on the entry, because a regeneration (#315) recomputes the
-- derived images and must leave these untouched. It is also why attachments are protected from the
-- platform's photo-count truncation (#309): whole generated groups are dropped from the end first.
--
-- `photoId` cascades deliberately. Deleting a copy's scan removes the attachment from *future*
-- plans, while the image already generated from it is a separate `photo` row and survives — exactly
-- the staleness the generation fingerprint reports. An `upload` attachment's photo is offer-owned
-- (`kind = 'original'`) and exists only for the attachment, so the application deletes that row and
-- its bytes when the attachment is removed; purging generated bytes later leaves the original
-- intact.

CREATE TABLE "offer_photo_attachment" (
    "id" TEXT NOT NULL,
    "offerId" TEXT NOT NULL,
    -- 0-based position in the finished plan; out-of-range values clamp to the end (#309).
    "sortOrder" INTEGER NOT NULL,
    -- copy_photo | upload
    "source" TEXT NOT NULL,
    "photoId" TEXT NOT NULL,
    -- The copy whose data annotates the tile (#312); NULL for an upload, whose inventory tokens
    -- resolve empty while the label template's literal text still renders.
    "itemId" TEXT,
    -- The collector's own caption, shown in the plan only — never drawn on the image.
    "title" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "offer_photo_attachment_pkey" PRIMARY KEY ("id")
);

-- The plan is always read in order, per offer.
CREATE INDEX "offer_photo_attachment_offerId_sortOrder_idx"
    ON "offer_photo_attachment"("offerId", "sortOrder");
CREATE INDEX "offer_photo_attachment_photoId_idx" ON "offer_photo_attachment"("photoId");
CREATE INDEX "offer_photo_attachment_itemId_idx" ON "offer_photo_attachment"("itemId");

ALTER TABLE "offer_photo_attachment"
    ADD CONSTRAINT "offer_photo_attachment_offerId_fkey"
    FOREIGN KEY ("offerId") REFERENCES "offer"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "offer_photo_attachment"
    ADD CONSTRAINT "offer_photo_attachment_photoId_fkey"
    FOREIGN KEY ("photoId") REFERENCES "photo"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "offer_photo_attachment"
    ADD CONSTRAINT "offer_photo_attachment_itemId_fkey"
    FOREIGN KEY ("itemId") REFERENCES "item"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- A copy attachment names the copy it renders from; an upload has none.
ALTER TABLE "offer_photo_attachment" ADD CONSTRAINT "offer_photo_attachment_source_item"
    CHECK (
        ("source" = 'copy_photo' AND "itemId" IS NOT NULL)
        OR ("source" = 'upload' AND "itemId" IS NULL)
    );
