import { describe, it, before, after } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync } from "node:fs";
import { rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import sharp from "sharp";
import { prisma } from "../../src/lib/db";
import { createItem } from "../../src/lib/items";
import {
  addOfferSet,
  createOffer,
  getOfferDetail,
  setOfferState,
  updateOfferPhotoConfig,
} from "../../src/lib/offers";
import { applyPhotoChangeSet, stageUpload } from "../../src/lib/photos";
import {
  claimNextOfferPhotoGeneration,
  enqueueOfferPhotoGeneration,
  runOfferPhotoGeneration,
} from "../../src/lib/offer-photo-generation";
import { setColnectConditionMapping } from "../../src/lib/colnect";

// Generated bytes land in a throwaway directory rather than the repo's `.data`. `dataDir()` reads the
// env var on every call, so setting it before any test body runs is enough.
const DATA_DIR = mkdtempSync(path.join(tmpdir(), "stamporama-ready-gate-"));
process.env.STAMPORAMA_DATA_DIR = DATA_DIR;

// The listing preconditions gating `preparing → ready` (#418). The rules themselves are unit-tested
// (`listing-preconditions.test.ts`) and their resolution is covered by the kit's own suite (#405);
// what needs a database here is the gate: which offers the transition refuses, which it lets through,
// and that the offer's own screen states the same reasons before the button is ever pressed.

describe("marking an offer ready (#418)", () => {
  let userId: string;
  let collectionId: string;
  /** The platform named as Colnect — the only one whose offers are checked. */
  let platformId: string;
  /** A platform with no Assistant module: listed by hand, so nothing is asked of its offers. */
  let handListedId: string;
  /** A platform whose module has no listing half (#355/#471) — Allegro's marker is about captured
   *  auction lots, so its offers are listed by hand exactly like the one above. */
  let allegroId: string;
  let mnhId: string;
  let usedId: string;

  before(async () => {
    const ts = Date.now();
    userId = `test-user-gate-${ts}`;
    await prisma.user.create({
      data: {
        id: userId,
        name: `Test User gate-${ts}`,
        email: `test-gate-${ts}@example.com`,
        emailVerified: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    });
    collectionId = (
      await prisma.collection.create({
        data: {
          slug: `col-gate-${ts}`,
          name: `Collection gate-${ts}`,
          baseCurrency: "EUR",
          ownerId: userId,
        },
      })
    ).id;
    mnhId = (
      await prisma.stampCondition.create({
        data: { collectionId, name: "Mint Never Hinged", abbreviation: "MNH", sortOrder: 0 },
      })
    ).id;
    usedId = (
      await prisma.stampCondition.create({
        data: { collectionId, name: "Used", abbreviation: "U", sortOrder: 1 },
      })
    ).id;
    platformId = (
      await prisma.contact.create({
        data: {
          collectionId,
          name: "Colnect",
          platform: true,
          platformModule: "colnect",
          platformCurrency: "EUR",
        },
      })
    ).id;
    handListedId = (
      await prisma.contact.create({
        data: { collectionId, name: "Delcampe", platform: true, platformCurrency: "EUR" },
      })
    ).id;
    allegroId = (
      await prisma.contact.create({
        data: {
          collectionId,
          name: "Allegro",
          platform: true,
          platformModule: "allegro",
          platformCurrency: "EUR",
        },
      })
    ).id;
    // Only MNH is mapped: the Used case is what the unmapped-condition refusal rides on.
    await setColnectConditionMapping(userId, mnhId, "1");
  });

  after(async () => {
    await prisma.collection.deleteMany({ where: { ownerId: userId } });
    await prisma.user.deleteMany({ where: { id: userId } });
  });

  let seq = 0;

  async function stamp(name: string, colnectId: string | null): Promise<string> {
    seq += 1;
    return (
      await prisma.stamp.create({ data: { collectionId, name: `${name} ${seq}`, colnectId } })
    ).id;
  }

  async function copy(stampId: string, conditionId = mnhId): Promise<string> {
    return (await createItem(userId, collectionId, { stampId, conditionId, forSale: true })).id;
  }

  /** A `preparing` offer over the given sets. */
  async function preparingOffer(sets: string[][], platform = platformId): Promise<string> {
    const offerId = await createOffer(userId, collectionId, {
      platformId: platform,
      url: null,
      price: "12.50",
      currency: "EUR",
      listingDate: null,
      state: "preparing",
    });
    for (const itemIds of sets) await addOfferSet(userId, offerId, itemIds);
    return offerId;
  }

  const stateOf = async (offerId: string) =>
    (await prisma.offer.findUnique({ where: { id: offerId }, select: { state: true } }))?.state;

  it("lets a listable offer through", async () => {
    const offerId = await preparingOffer([[await copy(await stamp("PL ok", "2001"))]]);
    await setOfferState(userId, offerId, "ready");
    assert.equal(await stateOf(offerId), "ready");
  });

  it("refuses a text over the platform's cap — on a platform with no Assistant at all (#636)", async () => {
    // The caps are the platform's, not a module's: an over-long title is refused where the listing
    // preconditions ask nothing, which is the case Delcampe's uploaded file made matter.
    const offerId = await preparingOffer(
      [[await copy(await stamp("PL long title", null), usedId)]],
      handListedId
    );
    await prisma.offer.update({
      where: { id: offerId },
      data: { name: "x".repeat(92) },
    });
    await prisma.contact.update({ where: { id: handListedId }, data: { maxTitleLength: 80 } });

    const detail = await getOfferDetail(userId, offerId);
    assert.deepEqual(
      detail?.readyBlockers.map((blocker) => blocker.code),
      ["title-too-long"]
    );
    await assert.rejects(
      () => setOfferState(userId, offerId, "ready"),
      /92 characters, 12 over this platform's 80/
    );
    assert.equal(await stateOf(offerId), "preparing");

    // Nothing was shortened to make it fit, and cutting the text is what unblocks it.
    const kept = await prisma.offer.findUniqueOrThrow({
      where: { id: offerId },
      select: { name: true },
    });
    assert.equal(kept.name?.length, 92);
    await prisma.offer.update({ where: { id: offerId }, data: { name: "x".repeat(80) } });
    await setOfferState(userId, offerId, "ready");
    assert.equal(await stateOf(offerId), "ready");

    await prisma.contact.update({ where: { id: handListedId }, data: { maxTitleLength: null } });
  });

  it("reports an offer that was already ready when the cap was tightened (#636)", async () => {
    // A Ready offer has no Ready gate left to fail, so what reports it is the listing gate the bulk
    // workspace draws its cards from — which is why the caps are read live and never seeded (#310).
    const offerId = await preparingOffer(
      [[await copy(await stamp("PL tightened", null), usedId)]],
      handListedId
    );
    await prisma.offer.update({ where: { id: offerId }, data: { name: "x".repeat(90) } });
    await setOfferState(userId, offerId, "ready");

    await prisma.contact.update({ where: { id: handListedId }, data: { maxTitleLength: 80 } });
    const detail = await getOfferDetail(userId, offerId);
    assert.equal(await stateOf(offerId), "ready", "the offer is not moved back by a settings change");
    assert.deepEqual(
      detail?.listingBlockers.map((blocker) => blocker.code),
      ["title-too-long"]
    );

    await prisma.contact.update({ where: { id: handListedId }, data: { maxTitleLength: null } });
  });

  it("refuses a stamp with no Colnect item-ID, and leaves the offer preparing", async () => {
    const offerId = await preparingOffer([[await copy(await stamp("PL unmatched", null))]]);
    await assert.rejects(
      () => setOfferState(userId, offerId, "ready"),
      /no catalog item-ID/
    );
    assert.equal(await stateOf(offerId), "preparing");
  });

  it("refuses a condition with no Colnect grade mapped", async () => {
    const offerId = await preparingOffer([
      [await copy(await stamp("PL ungraded", "2002"), usedId)],
    ]);
    await assert.rejects(
      () => setOfferState(userId, offerId, "ready"),
      /no grade mapped for this platform: Used/
    );
    assert.equal(await stateOf(offerId), "preparing");
  });

  it("refuses sets that are not interchangeable", async () => {
    const a = await stamp("PL mixed a", "2003");
    const b = await stamp("PL mixed b", "2004");
    const offerId = await preparingOffer([[await copy(a)], [await copy(a), await copy(b)]]);
    await assert.rejects(() => setOfferState(userId, offerId, "ready"), /not interchangeable/);
    assert.equal(await stateOf(offerId), "preparing");
  });

  it("asks nothing of a platform the Assistant has no module for", async () => {
    const offerId = await preparingOffer(
      [[await copy(await stamp("PL by hand", null), usedId)]],
      handListedId
    );
    await setOfferState(userId, offerId, "ready");
    assert.equal(await stateOf(offerId), "ready");
  });

  it("asks nothing of a platform whose module cannot list either (#471)", async () => {
    // Allegro names a module, but nothing here posts a sale form to it — so an offer of its own is
    // neither gated on Colnect's item-IDs nor shown a card of Colnect links.
    const offerId = await preparingOffer(
      [[await copy(await stamp("PL allegro", null), usedId)]],
      allegroId
    );
    const detail = await getOfferDetail(userId, offerId);
    assert.deepEqual(detail?.readyBlockers, []);
    assert.deepEqual(detail?.platformItems, [], "no Colnect catalogue card on an Allegro offer");
    await setOfferState(userId, offerId, "ready");
    assert.equal(await stateOf(offerId), "ready");
  });

  it("still draws the catalogue card for the platform that is Colnect (#423)", async () => {
    const offerId = await preparingOffer([[await copy(await stamp("PL card", "2101"))]]);
    const detail = await getOfferDetail(userId, offerId);
    assert.equal(detail?.platformItems.length, 1);
    assert.ok(detail?.platformItems[0].catalogUrl, "a matched stamp keeps its catalog link");
  });

  it("states the reasons on the offer's own screen while it is still preparing", async () => {
    const offerId = await preparingOffer([[await copy(await stamp("PL shown", null), usedId)]]);
    const detail = await getOfferDetail(userId, offerId);
    assert.deepEqual(
      detail?.readyBlockers.map((b) => b.code),
      ["missing-catalog-id", "unmapped-condition"]
    );
    // The Assistant's own blockers stay judged at the state the offer is *in* (#414).
    assert.deepEqual(detail?.listingBlockers.map((b) => b.code), ["not-ready"]);
  });

  it("says nothing about readiness once the offer is past that step", async () => {
    const offerId = await preparingOffer([[await copy(await stamp("PL live", "2005"))]]);
    await setOfferState(userId, offerId, "ready");
    const detail = await getOfferDetail(userId, offerId);
    assert.deepEqual(detail?.readyBlockers, []);
  });

  it("asks nothing about photos of an offer whose plan renders none", async () => {
    // No collage numbers on it and no attachment: there is nothing to generate, so the gate has
    // nothing to hold the offer for.
    const offerId = await preparingOffer([[await copy(await stamp("PL no plan", "2007"))]]);
    const detail = await getOfferDetail(userId, offerId);
    assert.deepEqual(detail?.readyBlockers, []);
    await setOfferState(userId, offerId, "ready");
    assert.equal(await stateOf(offerId), "ready");
  });

  it("never blocks stepping an offer back, or taking it out of the shop", async () => {
    const offerId = await preparingOffer([[await copy(await stamp("PL back", "2006"))]]);
    await setOfferState(userId, offerId, "ready");
    // The stamp loses its item-ID after the fact — the offer must still be movable.
    await prisma.stamp.updateMany({
      where: { name: { startsWith: "PL back" }, collectionId },
      data: { colnectId: null },
    });
    await setOfferState(userId, offerId, "preparing");
    assert.equal(await stateOf(offerId), "preparing");
    await setOfferState(userId, offerId, "withdrawn");
    assert.equal(await stateOf(offerId), "withdrawn");
  });
});

// The photo half of the same gate (#311). The rules are unit-tested
// (`offer-photo-readiness.test.ts`); what needs a database and a storage backend is that the
// transition actually reads a real photo plan — generated, stale, or never run — and that the offer's
// own screen states the same reason before the button is pressed. The platform here names no
// Assistant module on purpose, so nothing but the photos can hold the offer back.
describe("marking an offer ready with listing photos (#311)", () => {
  let userId: string;
  let collectionId: string;
  let platformId: string;
  let conditionId: string;

  before(async () => {
    const ts = Date.now();
    userId = `test-user-photo-gate-${ts}`;
    await prisma.user.create({
      data: {
        id: userId,
        name: `Test User photo-gate-${ts}`,
        email: `test-photo-gate-${ts}@example.com`,
        emailVerified: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    });
    collectionId = (
      await prisma.collection.create({
        data: {
          slug: `col-photo-gate-${ts}`,
          name: `Collection photo-gate-${ts}`,
          baseCurrency: "EUR",
          ownerId: userId,
        },
      })
    ).id;
    conditionId = (
      await prisma.stampCondition.create({
        data: { collectionId, name: "Used", abbreviation: "U", sortOrder: 0 },
      })
    ).id;
    platformId = (
      await prisma.contact.create({
        data: {
          collectionId,
          name: `Delcampe ${ts}`,
          platform: true,
          maxPhotos: 6,
          // A modest edge keeps the render fast; the gate never looks at the bytes.
          maxPhotoEdge: 600,
        },
      })
    ).id;
  });

  after(async () => {
    await prisma.collection.deleteMany({ where: { ownerId: userId } });
    await prisma.user.deleteMany({ where: { id: userId } });
    await rm(DATA_DIR, { recursive: true, force: true });
  });

  let seq = 0;

  /** A copy carrying one front scan — enough for the plan to have something to lay out. */
  async function scannedCopy(): Promise<string> {
    seq += 1;
    const stampRow = await prisma.stamp.create({
      data: { collectionId, name: `Photo stamp ${seq}`, primaryCatalogSortKey: seq },
    });
    const item = await createItem(userId, collectionId, {
      stampId: stampRow.id,
      conditionId,
      forSale: true,
    });
    const bytes = await sharp({
      create: { width: 120, height: 160, channels: 3, background: { r: 20 * seq, g: 120, b: 200 } },
    })
      .png()
      .toBuffer();
    const upload = await stageUpload(userId, collectionId, { bytes, mime: "image/png" });
    await applyPhotoChangeSet(userId, item.id, {
      add: [{ uploadId: upload.id, role: "front", title: null, sortOrder: 0 }],
      update: [],
      remove: [],
    });
    return item.id;
  }

  /** A `preparing` offer with a collage configured and one scanned copy — its plan holds one image. */
  async function offerWithPhotoPlan(): Promise<string> {
    const offerId = await createOffer(userId, collectionId, {
      platformId,
      url: null,
      price: "9.00",
      currency: "EUR",
      listingDate: null,
      state: "preparing",
    });
    await updateOfferPhotoConfig(userId, offerId, {
      photoSides: "front",
      preferSingles: false,
      photoLabelLeftTemplate: null,
      photoLabelRightTemplate: null,
      collage: {
        collageGridMode: "fixed" as const,
        collageRows: 2,
        collageColumns: 2,
        collageGapPercent: 8,
        collageBackground: "#ffffff",
        collageLabelPercent: 16,
      },
    });
    await addOfferSet(userId, offerId, [await scannedCopy()]);
    return offerId;
  }

  /** Stand in for the worker: enqueue, claim, render. */
  async function generate(offerId: string): Promise<void> {
    await enqueueOfferPhotoGeneration(userId, offerId);
    await claimNextOfferPhotoGeneration({ offerId });
    await runOfferPhotoGeneration(offerId);
  }

  const stateOf = async (offerId: string) =>
    (await prisma.offer.findUnique({ where: { id: offerId }, select: { state: true } }))?.state;

  it("refuses an offer whose photos were never generated, and says so on its screen", async () => {
    const offerId = await offerWithPhotoPlan();
    assert.deepEqual(
      (await getOfferDetail(userId, offerId))?.readyBlockers.map((b) => b.code),
      ["photos-missing"]
    );
    await assert.rejects(
      () => setOfferState(userId, offerId, "ready"),
      /no generated listing photos/
    );
    assert.equal(await stateOf(offerId), "preparing");
  });

  it("lets a generated offer through", async () => {
    const offerId = await offerWithPhotoPlan();
    await generate(offerId);
    assert.deepEqual((await getOfferDetail(userId, offerId))?.readyBlockers, []);
    await setOfferState(userId, offerId, "ready");
    assert.equal(await stateOf(offerId), "ready");
  });

  it("refuses photos left out of date by a change to the offer", async () => {
    const offerId = await offerWithPhotoPlan();
    await generate(offerId);
    // A second set changes what the plan would render — the stored image no longer shows the offer.
    await addOfferSet(userId, offerId, [await scannedCopy()]);
    assert.deepEqual(
      (await getOfferDetail(userId, offerId))?.readyBlockers.map((b) => b.code),
      ["photos-outdated"]
    );
    await assert.rejects(() => setOfferState(userId, offerId, "ready"), /out of date/);
    assert.equal(await stateOf(offerId), "preparing");

    // Regenerating is what clears it.
    await generate(offerId);
    await setOfferState(userId, offerId, "ready");
    assert.equal(await stateOf(offerId), "ready");
  });

  it("refuses while a run is still in flight", async () => {
    const offerId = await offerWithPhotoPlan();
    await enqueueOfferPhotoGeneration(userId, offerId);
    await assert.rejects(() => setOfferState(userId, offerId, "ready"), /still being generated/);
    assert.equal(await stateOf(offerId), "preparing");
  });

  it("never blocks a later transition over stale photos", async () => {
    const offerId = await offerWithPhotoPlan();
    await generate(offerId);
    await setOfferState(userId, offerId, "ready");
    // The composition changes under the live listing: it must still be publishable and withdrawable.
    await addOfferSet(userId, offerId, [await scannedCopy()]);
    await setOfferState(userId, offerId, "active");
    assert.equal(await stateOf(offerId), "active");
    await setOfferState(userId, offerId, "withdrawn");
    assert.equal(await stateOf(offerId), "withdrawn");
  });
});
