import { NextRequest, NextResponse } from "next/server";
import { headers } from "next/headers";
import { auth } from "@/lib/auth";
import { planAlbum } from "@/lib/album-plan";
import { renderAlbumPdf, AlbumPdfError } from "@/lib/album-pdf";

// The album as a printable file (#768).
//
// A route handler rather than a server action: this hands over bytes with a filename, which is what
// a `Content-Disposition` is for and what an action cannot do — the offer photo ZIP (#314) is the
// same shape for the same reason.
//
// `?sheets=` selects, in the positions the album screen has just listed. Absent means the whole
// album. Those numbers are a *request*, never an identity — a sheet is named by its catalog range
// (ADR-0045 §1) and this file is generated from the listing the collector is looking at.
//
// **Nothing is stored.** The bytes are composed on demand from a plan that is itself a derivation,
// so there is nothing here to go stale and nothing to sweep. Were they ever kept, they would be
// generated bytes and would take a TTL like every other generated byte (`storage-and-jobs.md`);
// that is a decision for whoever needs it, not a gap here.
export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ collectionId: string; albumId: string }> }
) {
  const session = await auth.api.getSession({ headers: await headers() });
  if (!session) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { collectionId, albumId } = await params;
  const plan = await planAlbum(session.user.id, albumId);
  // The album is resolved by owner, and then checked against the collection in the URL — an album
  // of the collector's own but of another collection is a 404 here, exactly as on its screen.
  if (!plan || plan.album.collectionId !== collectionId) {
    return NextResponse.json({ error: "Not found" }, { status: 404 });
  }

  let file;
  try {
    file = await renderAlbumPdf(plan, request.nextUrl.searchParams.get("sheets"));
  } catch (err) {
    if (err instanceof AlbumPdfError) {
      return NextResponse.json({ error: err.message }, { status: 400 });
    }
    throw err;
  }

  return new Response(new Uint8Array(file.bytes), {
    status: 200,
    headers: {
      "Content-Type": "application/pdf",
      "Content-Length": String(file.bytes.byteLength),
      // `attachment`, not `inline`: a viewer's own zoom proves nothing about millimetres, and the
      // file is meant to be kept and re-printed unchanged.
      "Content-Disposition": `attachment; filename*=UTF-8''${encodeURIComponent(file.fileName)}`,
      // A live page re-plans on every read, so a cached file would be a card that disagrees with
      // the screen that offered it.
      "Cache-Control": "no-store",
    },
  });
}
