-- Persisted generated offer images and their background generation (#311).
--
-- Three moves:
--
-- 1. `photo.kind` — how the bytes came to exist: an `original` scan/upload of something physical, or
--    an image `generated` by the app. Every existing row is an original, which the default backfills.
--    Beyond describing the row this enables a later storage optimisation: generated bytes can be
--    purged and recreated on demand, originals never can.
--
-- 2. `photo.offerId` — a **third owner**, beside `itemId` (#112) and `stampId` (#137). A listing image
--    belongs to neither a copy nor a stamp: a collage is composited from several copies, and an image
--    uploaded straight to the offer (#313) has no copy at all. The owner XOR therefore becomes a
--    "exactly one of three" check, and the per-owner partial unique `(*, role)` index is added for the
--    new owner too. Offer images all carry `role = NULL` (their order lives in the plan table), and
--    NULLs stay distinct in Postgres, so that index never actually bites — it is there to keep the
--    invariant uniform across owners once #313 can attach a front/back image to an offer.
--
-- 3. Two new tables. `offer_photo_generation` is the job: one row per offer, both the queue entry and
--    the state the panel reads. `offer_photo_entry` is the plan metadata pointing at each generated
--    `photo` — order, what it was produced from, which side, its front/back pair, the sets that fed
--    it. Plan metadata does not belong on `photo`, which describes a file.
--
-- Staleness lives on the generation row as a `fingerprint` of the generator's inputs. It is a signal
-- only: images are never regenerated on download, and while nothing has changed the stored files are
-- simply served.

ALTER TABLE "photo"
    ADD COLUMN "kind" TEXT NOT NULL DEFAULT 'original',
    ADD COLUMN "offerId" TEXT;

-- Exactly one owner, now across three columns. `num_nonnulls` says this directly; the old two-column
-- `<>` form cannot express it.
ALTER TABLE "photo" DROP CONSTRAINT "photo_owner_xor";
ALTER TABLE "photo" ADD CONSTRAINT "photo_owner_xor"
    CHECK (num_nonnulls("itemId", "stampId", "offerId") = 1);

CREATE INDEX "photo_offerId_idx" ON "photo"("offerId");

CREATE UNIQUE INDEX "photo_offerId_role_key" ON "photo"("offerId", "role")
    WHERE "offerId" IS NOT NULL;

ALTER TABLE "photo" ADD CONSTRAINT "photo_offerId_fkey"
    FOREIGN KEY ("offerId") REFERENCES "offer"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- The generation job / state. At most one row per offer (unique `offerId`): Generate re-queues the
-- same row rather than piling up jobs, so pressing it twice is one render, not two.
CREATE TABLE "offer_photo_generation" (
    "id" TEXT NOT NULL,
    "offerId" TEXT NOT NULL,
    -- queued | running | ready | failed
    "status" TEXT NOT NULL DEFAULT 'queued',
    -- Inputs the *stored* images were produced from; NULL until a run has succeeded.
    "fingerprint" TEXT,
    "plannedCount" INTEGER NOT NULL DEFAULT 0,
    "renderedCount" INTEGER NOT NULL DEFAULT 0,
    "error" TEXT,
    "queuedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "startedAt" TIMESTAMP(3),
    "finishedAt" TIMESTAMP(3),

    CONSTRAINT "offer_photo_generation_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "offer_photo_generation_offerId_key" ON "offer_photo_generation"("offerId");

-- The worker claims the oldest queued row; the index serves exactly that query.
CREATE INDEX "offer_photo_generation_status_queuedAt_idx"
    ON "offer_photo_generation"("status", "queuedAt");

ALTER TABLE "offer_photo_generation"
    ADD CONSTRAINT "offer_photo_generation_offerId_fkey"
    FOREIGN KEY ("offerId") REFERENCES "offer"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- One image of the plan. `setIds` is a plain array, not a join table: a group can cover several
-- single-copy sets (#309 chunking), and the plan is a snapshot of what was rendered — a set removed
-- afterwards is the staleness the fingerprint reports, not a referential error to repair.
CREATE TABLE "offer_photo_entry" (
    "id" TEXT NOT NULL,
    "offerId" TEXT NOT NULL,
    "photoId" TEXT NOT NULL,
    "sortOrder" INTEGER NOT NULL,
    -- collage | copy_photo | upload  (the latter two arrive with manual attachments, #313)
    "source" TEXT NOT NULL DEFAULT 'collage',
    -- front | back for a collage; NULL for an attachment, which has no side.
    "side" TEXT,
    -- Links the front/back pair rendered from the same copies.
    "pairKey" TEXT,
    "setIds" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "offer_photo_entry_pkey" PRIMARY KEY ("id")
);

-- One entry per generated photo, and the plan is always read in order.
CREATE UNIQUE INDEX "offer_photo_entry_photoId_key" ON "offer_photo_entry"("photoId");
CREATE INDEX "offer_photo_entry_offerId_sortOrder_idx"
    ON "offer_photo_entry"("offerId", "sortOrder");

ALTER TABLE "offer_photo_entry"
    ADD CONSTRAINT "offer_photo_entry_offerId_fkey"
    FOREIGN KEY ("offerId") REFERENCES "offer"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "offer_photo_entry"
    ADD CONSTRAINT "offer_photo_entry_photoId_fkey"
    FOREIGN KEY ("photoId") REFERENCES "photo"("id") ON DELETE CASCADE ON UPDATE CASCADE;
